name: Build Menu_Ubuntu.zip
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            qtbase5-dev \
            qttools5-dev \
            libqt5svg5-dev \
            libqt5x11extras5-dev \
            libkf5windowsystem-dev \
            libkf5globalaccel-dev \
            baloo-kf5-dev \
            libxtst-dev \
            libxdamage-dev \
            libxcomposite-dev \
            libxrender-dev \
            libxcb1-dev \
            libx11-xcb-dev \
            libxcb-damage0-dev \
            libxcb-util-dev \
            libxcb-ewmh-dev \
            libdbusmenu-qt5-dev \
            libkf5dbusaddons-dev \
            libpulse-dev \
            libqalculate-dev \
            qtdeclarative5-dev \
            libprocps-dev \
            make \
            pkg-config \
            libicu-dev

      - name: Build Menu_Ubuntu.zip
        run: |
          mkdir build ; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make DESTDIR=. install
          find System/Menu.app/
          cd ./System/
          zip --symlinks -r ../Menu_Ubuntu.zip Menu.app/

      - name: Upload Menu_Ubuntu.zip
        uses: actions/upload-artifact@v2
        with:
          name: Menu_Ubuntu.zip
          path: build/Menu_Ubuntu.zip
          
      - name: Create GitHub Release using Continuous Release Manager
        if: github.event_name == 'push'  # Only run for push events, not pull requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -o continuous-release-manager-linux https://github.com/probonopd/continuous-release-manager/releases/download/continuous/continuous-release-manager-linux
          chmod +x continuous-release-manager-linux
          ./continuous-release-manager-linux

      - name: Upload to GitHub Release
        if: github.event_name == 'push'  # Only run for push events, not pull requests
        run: |
          gh release upload continuous ./build/Menu_Ubuntu.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
